version: 2

build:
  os: ubuntu-24.04
  tools:
    python: '3.12'
  jobs:
    post_install:
      - python -m pip install --upgrade pip poetry
      - poetry install --with docs

sphinx:
  configuration: docs/conf.py
