version: 2

build:
  os: ubuntu-24.04
  tools:
    python: '3.12'

sphinx:
  configuration: docs/conf.py

python:
  install:
    # 1) Install package into RTD's venv
    - method: pip
      path: .
    # 2) Install doc dependencies into the same venv
    - requirements: docs/requirements.txt
